spring:
  application:
    name: quiz
  datasource:
    url: jdbc:mysql://localhost:3306/home_db
    username: user
    password: qwer1234!@
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

server:
  port: 8081