version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: home-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: home_db
      MYSQL_USER: user
      MYSQL_PASSWORD: qwer1234!@
    ports:
      - "3306:3306"
    volumes:
      - home_mysql_data:/var/lib/mysql
    networks:
      - home-network
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password

volumes:
  home_mysql_data:

networks:
  home-network:
    driver: bridge